# This compose file creates the multimodal search query app,
# and a suitable PostgreSQL database with the pgvector plugin built in.

services:

  mm-search-query-app:
    build:
      context: ./query_app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mm-search-postgres-db:5432/${POSTGRES_DB}
    depends_on:
      mm-search-postgres-db:
       condition: service_healthy

  mm-search-postgres-db:
   image: pgvector/pgvector:pg17
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
     interval: 5s
     timeout: 5s
     retries: 5
