# This compose file assumes that there is a PostgreSQL database running at
# $DATABASE_URL. This compose file does not attempt to create or manage that
# database in any way. The PG database needs to have the pgvector extension
# installed.

services:
  mm-search-query-app:
    build:
      context: ./query_app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
